### ISSUE TITLE
Remove yaml file after being sent to Telegram.

### ISSUE THREAD

**Issue by irvifa** [cloudnative-id/kubeweekly-telegram-bot#2]
The idea is actually waiting for the file to be written/or directly send to the python bot and then send it to Telegram and delete it.

**Comment by irvifa** [comment]
I'm planning to use https://github.com/cloudnative-id/kubeweekly-scrapper as init container. cc @2pai and @girikuncoro

**Comment by zufardhiyaulhaq** [comment]
@irvifa, the program is not writing any YAML files. 
@2pai requests to change the code to match the following behavior:

- store previous kubeweekly data from  `kubeweekly-scrapper`
- make decision-based on stored data (send or not send).

**Comment by irvifa** [comment]
Okay, that way we can make the scrapper as an init container. Since we can only start the telegram bot after we scrap the data. Can you please edit the behavior of your program? I'd like to fix the kube job in the other repo as well 🙇 @zufardhiyaulhaq

**Comment by zufardhiyaulhaq** [comment]
@irvifa okey, WIP

**Comment by irvifa** [comment]
Related PR:
- https://github.com/cloudnative-id/kubeops/pull/3

**Comment by zufardhiyaulhaq** [comment]
Pull Request:
- https://github.com/cloudnative-id/kubeweekly-telegram-bot/pull/4
